# Generated by Django 3.1.1 on 2020-09-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idJogo', models.IntegerField()),
                ('placar', models.IntegerField(max_length=3)),
                ('placarMin', models.IntegerField()),
                ('placarMax', models.IntegerField()),
                ('quebraRecMin', models.IntegerField()),
                ('quebraRecMax', models.IntegerField()),
            ],
        ),
    ]
