# Generated by Django 3.1 on 2020-10-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='id',
        ),
        migrations.AlterField(
            model_name='jogo',
            name='idJogo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='placar',
            field=models.IntegerField(),
        ),
    ]
